config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  scope module: 'web' do
    root 'home#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    delete 'auth/logout', to: 'auth#destroy'
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    resources :repositories, only: %i[index show new create] do
      resources :checks, only: %i[create show], module: 'repositories'
    end
  end

  namespace :api do
    resources :checks, only: %i[create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/repository.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repositories
#
#  id         :integer          not null, primary key
#  clone_url  :string
#  full_name  :string
#  language   :string
#  name       :string
#  ssh_url    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  github_id  :string
#  user_id    :integer          not null
#
# Indexes
#
#  index_repositories_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Repository < ApplicationRecord
  extend Enumerize

  belongs_to :user
  has_many :checks, class_name: 'Repository::Check', dependent: :destroy

  enumerize :language, in: %i[javascript ruby], default: nil, allow_nil: true
end

app/models/repository/check.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repository_checks
#
#  id            :integer          not null, primary key
#  aasm_state    :string
#  passed        :boolean          default(FALSE)
#  result        :json
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  commit_id     :string
#  repository_id :integer          not null
#
# Indexes
#
#  index_repository_checks_on_repository_id  (repository_id)
#
# Foreign Keys
#
#  repository_id  (repository_id => repositories.id)
#
class Repository::Check < ApplicationRecord
  include AASM

  belongs_to :repository, class_name: 'Repository', inverse_of: :checks

  aasm do
    state :pending, initial: true
    state :in_progress
    state :finished
    state :failed

    event :start do
      transitions from: :pending, to: :in_progress
    end

    event :complete do
      transitions from: :in_progress, to: :finished
    end

    event :fail do
      transitions from: :in_progress, to: :failed
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  email      :string
#  nickname   :string
#  token      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  has_many :repositories, dependent: :destroy
end

app/controllers/api/application_controller.rb
# frozen_string_literal: true

class Api::ApplicationController < ApplicationController
  skip_before_action :verify_authenticity_token

  def check_github_secret_token
    return true unless ENV.fetch('GITHUB_SECRET_TOKEN', nil)

    calculated_signature = OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), ENV.fetch('GITHUB_SECRET_TOKEN', nil), request.raw_post)
    signature_from_request = request.headers['HTTP_X_HUB_SIGNATURE_256'].delete_prefix('sha256=')

    head :forbidden unless Rack::Utils.secure_compare(calculated_signature, signature_from_request)
  end
end

app/controllers/api/checks_controller.rb
# frozen_string_literal: true

class Api::ChecksController < Api::ApplicationController
  before_action :check_github_secret_token

  def create
    check = repository.checks.build

    if check.save
      Repository::CheckJob.perform_later(check_id: check.id)

      head :ok
    else
      head :not_found
    end
  end

  def repository
    @repository ||= Repository.find_by(github_id: params.dig(:repository, :id))
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/concerns/authentication.rb
# frozen_string_literal: true

module Authentication
  extend ActiveSupport::Concern

  included do
    helper_method :current_user, :user_signed_in?
  end

  def authenticate_user!
    redirect_to root_path, alert: t('need_login') unless current_user
  end

  def current_user
    Current.user || authenticate_user_from_session
  end

  def user_signed_in?
    current_user.present?
  end

  def authenticate_user_from_session
    User.find_by(id: session[:user_id])
  end

  def sign_in(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def sign_out
    Current.user = nil
    reset_session
  end
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
  include Authentication
end

app/controllers/web/auth_controller.rb
# frozen_string_literal: true

class Web::AuthController < Web::ApplicationController
  def callback
    auth_params = request.env['omniauth.auth']
    user = User::FindOrCreate.run(auth_params:)

    if user.valid?
      sign_in(user.result)
      flash[:notice] = t('login.success')
    else
      flash[:alert] = t('login.failure')
    end

    redirect_to root_path
  end

  def destroy
    sign_out

    redirect_to root_path, notice: t('.logout.success')
  end
end

app/controllers/web/home_controller.rb
# frozen_string_literal: true

class Web::HomeController < Web::ApplicationController
  def index; end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

class Web::Repositories::ChecksController < Web::ApplicationController
  before_action :authenticate_user!

  def show
    @check = repository.checks.find(params[:id])

    redirect_to repository_path(repository), alert: t('.not_finished') unless @check.finished?
  end

  def create
    check = repository.checks.new
    if check.save
      flash[:notice] = t('.success')
      Repository::CheckJob.perform_later(check_id: check.id)
      redirect_to repository_path(repository)
    else
      flash[:alert] = t('.failure')
      redirect_to repositories_path
    end
  end

  private

  def repository
    @repository ||= current_user.repositories.find(params[:repository_id])
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

class Web::RepositoriesController < Web::ApplicationController
  before_action :authenticate_user!

  def index
    @repositories = current_user.repositories.includes(:checks)
  end

  def show
    @repository = current_user.repositories.find(params[:id])

    @checks = @repository.checks.order(created_at: :desc)
  end

  def new
    @repository = current_user.repositories.new

    output = Github::FetchRepositories.run(user: current_user)

    if output.valid?
      @github_repositories = output.result
    else
      flash[:alert] = output.errors.messages[:base].to_sentence
      redirect_to repositories_path
    end
  end

  def create
    output = Repository::Create.run(user: current_user, github_id: repository_params[:github_id])

    if output.valid?
      flash[:notice] = t('.success')
      redirect_to output.result
    else
      flash[:alert] = t('.errors')
      @repository = output
      redirect_to new_repository_path
    end
  end

  def repository_params
    params.require(:repository).permit(:github_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :success
      'success'
    when :error
      'danger'
    when :alert
      'warning'
    when :notice
      'info'
    else
      flash_type.to_s
    end
  end

  def attr_or_dash(attr)
    attr.presence || '-'
  end
end

app/helpers/web/home_helper.rb
# frozen_string_literal: true

module Web
  module HomeHelper
  end
end

app/helpers/web/repositories/checks_helper.rb
# frozen_string_literal: true

module Web::Repositories::ChecksHelper
  GITHUB_URL = 'https://github.com'

  def github_commit_link(repository, sha)
    "#{GITHUB_URL}/#{repository.full_name}/commit/#{sha}"
  end

  def github_file_link(repository, path, sha)
    "#{GITHUB_URL}/#{repository.full_name}/tree/#{sha}/#{path}"
  end
end

app/helpers/web/repositories_helper.rb
# frozen_string_literal: true

module Web::RepositoriesHelper
end

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title = t('.title')
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application',
      'data-turbo-track': 'reload',
      type: 'module'

  body.d-flex.flex-column.h-100
    = render 'layouts/shared/navbar'
    main
      .mt-4.mb-5.pb-5
        .container
          = render 'layouts/shared/flash'
          .p-4.align-items-center.border.shadow.bg-white.rounded-3
            .mb-4
              = yield
    = render 'layouts/shared/footer'

app/views/layouts/shared/_flash.html.slim
- flash.each do |key, value|
  = content_tag :div, value, class: "alert alert-#{key} alert-dismissible fade show",
    role: 'alert'
    button.close aria-label="Close" data-dismiss="alert" type="button"
      span aria-hidden="true" &times;

app/views/layouts/shared/_footer.html.slim
footer.bg-dark.text-light.mt-auto
  .container-xl
    .row.py-2
        .col-12.text-center
            | © #{Time.current.year} #{t('app_name')}

app/views/layouts/shared/_navbar.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand.me-md-4' do
        = image_tag 'logo.png', alt: 'logo', style: 'width: 30px;'
      ul.nav.nav-pills
        ul.nav-item.me-2
          = link_to root_path, class: 'nav-link link-dark' do
            = t('.home')
        - if current_user
          = link_to repositories_path, class: 'nav-link link-dark' do
            = t('.repositories')
    ul.nav.nav-pills
      - if current_user
        li.nav-item
          a.nav-link.text-secondary#user-email data-controller="emoji"
            = current_user.email
        li.nav-item
          = button_to auth_logout_url, method: :delete, class: 'nav-link link-dark' do
            = t('.sign_out')
      - else
        li.nav-item.me-2
          = button_to auth_request_path('github'), method: :post, data: { turbo: false }, class: 'nav-link link-dark'
            = t('.sign_in')

app/views/web/home/index.html.slim
h1.display-4.fw-bold.mb-0
  = t('.title')
p.mb-4
  = t('.description')
h2.display-6.fw-bold.mb-0
  = t('.subtitle')
p
  = t('.subdescription')

app/views/web/repositories/_form.html.slim
= simple_form_for repository do |f|
  = f.input :github_id, collection: @github_repositories, label_method: :name, value_method: :github_id, include_blank: false
  = f.button :submit, class: 'btn-primary'

app/views/web/repositories/checks/_list.html.slim
- if checks.any?
  table.table.table-striped
    thead
      tr
        th
        th scope='col'
          = t('check.attributes.aasm_state')
        th scope='col'
          = t('check.attributes.commit_id')
        th scope='col'
          = t('check.attributes.passed')
        th scope='col'
          = t('check.attributes.created_at')
    tbody
    - checks.each do |check|
      tr
        td
          = link_to check.id, repository_check_path(check.repository, check)
        td = check.aasm_state
        td = check.commit_id ? link_to(check.commit_id, github_commit_link(check.repository, check.commit_id)) : '-'
        td = check.passed
        td = check.created_at

app/views/web/repositories/checks/show.html.slim
= link_to t('back_to_repository'), repository_path(@check.repository), class: 'btn btn-primary'

h1.mt-4 = t('checks.show.title', id: @check.id)

table.table
  tbody
    tr
      td = t('.created_at')
      td = @check.created_at
    tr
      td = t('.aasm_state')
      td = @check.aasm.human_state
    tr
      td = t('.errors_count')
      td = @check.result&.size || 0
    tr
      td = t('.passed')
      td = @check.passed?
    tr
      td = t('.commit_id')
      td = link_to @check.commit_id, github_commit_link(@check.repository, @check.commit_id), target: '_blank', rel: 'noopener'

- if @check.result&.any?
  table.table.table-hover.mb-5
    thead
      tr
        th = t('check.errors.file')
        th = t('check.errors.rule')
        th = t('check.errors.location')
    tbody
      - @check.result.each do |error|
        tr
          td[colspan=3] = link_to error['file'], github_file_link(@check.repository, error['file'], @check.commit_id), target: '_blank', rel: 'noopener'
        tr
          td = error['message']
          td = error['rule']
          td = error['location']

app/views/web/repositories/index.html.slim
= link_to new_repository_path, class: 'btn btn-primary' do
  = t('.new_repository')

- if @repositories.any?
  table.table.table-striped.table-hover.mt-4
    thead
      tr
        th = t('repository.attributes.name')
        th = t('repository.attributes.language')
        th = t('.last_cheks_status')
    tbody
      - @repositories.each do |repository|
        tr
          td = link_to attr_or_dash(repository.name),
              repository_path(repository)
          td = attr_or_dash(repository.language)
          td = repository.checks.last ? repository.checks.last.aasm.human_state : t('.empty_checks')

app/views/web/repositories/new.html.slim
= render 'form',
  github_repositories: @github_repositories, repository: @repository

app/views/web/repositories/show.html.slim
h1 = @repository.full_name

= link_to t('.run_check'),
  repository_checks_path(@repository),
  class: 'btn btn-primary',
  data: { turbo_method: :post }

p.mt-4
  strong.me-2 = t('repository.attributes.name')
  = attr_or_dash(@repository.full_name)

p
  strong.me-2 = t('repository.attributes.language')
  = attr_or_dash(@repository.language)

p
  strong.me-2 = t('repository.attributes.created_at')
  = @repository.created_at

p
  strong.me-2 = t('repository.attributes.updated_at')
  = @repository.updated_at

= render 'web/repositories/checks/list', checks: @repository.checks

= link_to t('.back'), repositories_path, class: 'btn btn-secondary'